ssl:
  enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/persistence
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    suffix: .html
    enabled: true